### ISSUE TITLE
Validate compatibility with ansible-core 2.19

### ISSUE THREAD

**Issue by samccann** [ansible-collections/ansible.netcommon#698]
Copied from samccann/experiments#10

 ansible-core has implemented an extensive rewrite of templating and error handling as part of the [data tagging feature ](https://github.com/ansible/ansible/pull/84621) coming in core-2.19. You can find information about this change in that PR description, as well as in the [core 2.19 porting guide](https://docs.ansible.com/ansible-core/devel/porting_guides/porting_guide_core_2.19.html). 
 
 Please read  [background and testing requests,](https://forum.ansible.com/t/data-tagging-preview-and-testing/40759) which details where you can file potential bugs.

Collections that are part of the Ansible community package MUST test against `ansible-core 2.19` to ensure they continue to work with the updated core. Collections which are not compatible with `ansible-core 2.19`  will be removed from Ansible 12.  You can choose to test against the `stable-2.19` branch, the `devel` branch, the `milestone` branch, or the pre-release/released versions of `ansible-core 2.19` available on [Pypi](https://pypi.org/project/ansible-core/#history).

This should be an ongoing verification/check until the release of core 2.19 to ensure compatibility with any bugfixes or changes that happen until then.

You can find advice from fellow maintainers at [Making a collection compatible with data tagging](https://forum.ansible.com/t/making-a-collection-compatible-with-data-tagging/41717), and we welcome your additions to that forum topic.
 
 **Note:** You are not required to implement data tagging as part of this request, though we do recommend you consider where it can improve the quality of your collection. This issue is focused on ensuring you have verified your collection works with `ansible-core 2.19` in order to remain included in the Ansible 12 community package.
 
 We ask that you resolve any problems and link those PRs to this issue. If you do not find any problems with your integration/unit testing, please provide that comment and a pointer to your test results before closing this issue as done.
 
 You can reach out on the [Ansible forum](https://forum.ansible.com/t/data-tagging-preview-and-testing/40759) for more help or discussion.

**Comment by omnom62** [comment]
It seems to be broken due to this update - I am testing with an Ansible module, which is dependant on ansible.netcommon (v.8.0.0) and the module fails with `FAILED! => {"changed": false, "msg": "Task failed: ActionBase._parse_returned_data() missing 1 required positional argument: 'profile'"}`
netcommon/plugins/action/network.py: 341 `data = self._parse_returned_data(dict_out)` still uses the old signature

**Comment by moreati** [comment]
Still present with Ansible 12.0.0a9 and ansible-core 2.19.0rc2

<details>

```console
➜  netcommon_netconf_get git:(main) ✗ tox
py3.13-ansible11: venv> /Users/alex/.local/share/uv/tools/tox/bin/uv venv -p /Users/alex/.local/share/uv/tools/tox/bin/python --allow-existing --python-preference system /Users/alex/tmp/netcommon_netconf_get/.tox/py3.13-ansible11
py3.13-ansible11: install_deps> /Users/alex/.local/share/uv/tools/tox/bin/uv pip install 'ansible~=11.0' ncclient
py3.13-ansible11: commands[0]> ansible-playbook netcommon_netconf_get.yml

PLAY [localhost] **************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Show Ansible version] ***************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "ansible_version.full": "2.18.6"
}

TASK [Pull container] *********************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Start container] ********************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [Wait for container to start] ********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Get state] **************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Cleanup container] ******************************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************************
localhost                  : ok=7    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

py3.13-ansible11: OK ✔ in 14.19 seconds
py3.13-ansible12: venv> /Users/alex/.local/share/uv/tools/tox/bin/uv venv -p /Users/alex/.local/share/uv/tools/tox/bin/python --allow-existing --python-preference system /Users/alex/tmp/netcommon_netconf_get/.tox/py3.13-ansible12
py3.13-ansible12: install_deps> /Users/alex/.local/share/uv/tools/tox/bin/uv pip install 'ansible-core>=2.19.0b4' 'ansible>=12.0a' ncclient
py3.13-ansible12: commands[0]> ansible-playbook netcommon_netconf_get.yml

PLAY [localhost] **************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Show Ansible version] ***************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "ansible_version.full": "2.19.0rc2"
}

TASK [Pull container] *********************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Start container] ********************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [Wait for container to start] ********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Get state] **************************************************************************************************************************************************************************************************************
[ERROR]: Task failed: ActionBase._parse_returned_data() missing 1 required positional argument: 'profile'
Origin: /Users/alex/tmp/netcommon_netconf_get/netcommon_netconf_get.yml:29:11

27             timeout: 5
28
29         - name: Get state
             ^ column 11

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Task failed: ActionBase._parse_returned_data() missing 1 required positional argument: 'profile'"}

TASK [Cleanup container] ******************************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************************
localhost                  : ok=6    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

py3.13-ansible12: exit 2 (11.23 seconds) /Users/alex/tmp/netcommon_netconf_get> ansible-playbook netcommon_netconf_get.yml pid=14194
  py3.13-ansible11: OK (14.19=setup[1.89]+cmd[12.30] seconds)
  py3.13-ansible12: FAIL code 2 (14.30=setup[3.07]+cmd[11.23] seconds)
  evaluation failed :( (28.60 seconds)
```

</details>

**Comment by R3DW1N3** [comment]
Still broken with the release of Ansible 2.19.0

**Comment by gundalow** [comment]
A [PR has been started](https://github.com/ansible-collections/ansible.netcommon/pull/708), though it’s still work in progress

**Comment by felixfontein** [comment]
There's a deprecation warning with ansible-core 2.19 when using network_cli modules:
```
[DEPRECATION WARNING]: Passing `warnings` to `exit_json` or `fail_json` is deprecated. This feature will be removed from ansible-core version 2.23. Use `AnsibleModule.warn` instead.
```
