### ISSUE TITLE
Merged #635 Causing Downstream issue in Collection cisco.ios

### ISSUE THREAD

**Issue by happly** [ansible-collections/ansible.netcommon#639]
##### SUMMARY
Installing collection cisco.ios v8.0.0 pulls in ansible.netcommon by the logic [ansible.netcommon](https://galaxy.ansible.com/ui/repo/published/ansible/netcommon/): >=6.1.0 seen on the [dependencies](https://galaxy.ansible.com/ui/repo/published/cisco/ios/dependencies/) page.

Since the merging of #635 and release of v6.1.2, this is the latest dependency pulled in during the installation of cisco.ios collection.

When ansible.netcommon v6.1.2 is used with cisco.ios.ios_interfaces modules the following error is returned:

```
{
  "module_stdout": "",
  "module_stderr": "edit_config() got an unexpected keyword argument 'err_responses'",
  "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
  "_ansible_no_log": false,
  "changed": false
}
```
Note the mention of unexpected kwargs 'err_responses'; this argument seems to have been introduced in #635 .

When ansible.netcommon is pinned to v6.1.1, cisco.ios.ios_interfaces completes successfully.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- ansible.netcommon v6.1.2
- #635
- cisco.ios v8.0.0
- cisco.ios.ios_interfaces

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.12]
  config file = None
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.18 (main, Jan 24 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /runner/requirements_collections/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 6.1.2  

# /runner/requirements_collections/ansible_collections
Collection Version
---------- -------
cisco.ios  8.0.0  

# /runner/requirements_collections/ansible_collections
Collection    Version
------------- -------
ansible.utils 4.1.0  
```

##### CONFIGURATION

```paste below
[0;33mANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True[0m
[0;33mCOLLECTIONS_PATHS(env: ANSIBLE_COLLECTIONS_PATH) = ['/runner/requirements_collections', '/runner/.ansible/collections', '/usr/share/ansible/collections'][0m
[0;33mCONFIG_FILE() = None[0m
[0;33mDEFAULT_CALLBACK_PLUGIN_PATH(env: ANSIBLE_CALLBACK_PLUGINS) = ['/usr/local/lib/python3.9/site-packages/ansible_runner/display_callback/callback'][0m
[0;33mDEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = ['/runner/requirements_roles', '/runner/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles'][0m
[0;33mDEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = awx_display[0m
[0;33mHOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False[0m
[0;33mINVENTORY_UNPARSED_IS_FAILED(env: ANSIBLE_INVENTORY_UNPARSED_FAILED) = True[0m
[0;33mRETRY_FILES_ENABLED(env: ANSIBLE_RETRY_FILES_ENABLED) = False[0m
```

##### OS / ENVIRONMENT
AWX EE quay.io/ansible/awx-ee:latest (sha256:e9dc6bd5952a3d2e87bc1a3e5c12b88e9ba62e97a2e7b6beb8a80a597f217e9c)

Cisco IOS XE Software, Version 17.09.04a
Cisco IOS Software [Cupertino], Catalyst L3 Switch Software (CAT9K_IOSXE), Version 17.9.4a, RELEASE SOFTWARE (fc3)

##### STEPS TO REPRODUCE

- Install cisco.ios v8.0.0
- Run playbook against switch

```yaml
- name: Change Port Description
  hosts: all
  gather_facts: false
  tasks:
    - name: Change Description
      become: true
      cisco.ios.ios_interfaces:
        config:
          - name: "GigabitEthernet1/0/46"
            description: "beep boop bop"
```

##### EXPECTED RESULTS
Cisco interface port description modified

##### ACTUAL RESULTS

```
{
  "module_stdout": "",
  "module_stderr": "edit_config() got an unexpected keyword argument 'err_responses'",
  "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
  "_ansible_no_log": false,
  "changed": false
}
```

**Comment by NilashishC** [comment]
@happly This has been fixed with https://github.com/ansible-collections/ansible.netcommon/pull/640. We will do a netcommon release soon.

**Comment by happly** [comment]
@NilashishC Thank you for the quick fix!

**Comment by NilashishC** [comment]
This has been fixed with ansible.netcommon v6.1.3. Thanks!

**Comment by happly** [comment]
Confirming that 6.1.3 resolves the issue.
