### ISSUE TITLE
Request to release new netcommon version since getting an error while running the collections with existing netcommon version

### ISSUE THREAD

**Issue by komalupatil** [ansible-collections/ansible.netcommon#35]
##### SUMMARY
getting an error when try to run the collections for our dellemc.os6 while using it with ansible.netcommon version 0.0.2.

Below is the error we receive while running the playbook:

The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 645, in _execute
    result = self._handler.run(task_vars=variables)
  File "/root/.ansible/collections/ansible_collections/dellemc/os9/plugins/action/os9.py", line 94, in run
    result = super(ActionModule, self).run(task_vars=task_vars)
  File "/root/.ansible/collections/ansible_collections/ansible/netcommon/plugins/action/network.py", line 43, in run
    self._handle_src_option()
  File "/root/.ansible/collections/ansible_collections/ansible/netcommon/plugins/action/network.py", line 186, in _handle_src_option
    with self._templar.set_temporary_context(searchpath=searchpath):
AttributeError: 'Templar' object has no attribute 'set_temporary_context'
fatal: [leaf1]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""

The latest code for netcommon has some changes in ansible/netcommon/plugins/action/network.py file which is in version 0.0.3-dev19 onwards. 
Since those changes are not there in existing netcommon i.e., 0.0.2, we are getting above error. 

Playbook runs fine when i manually do the changes to the ansible/netcommon/plugins/action/network.py file which are there in 0.0.3-dev19 version. 

Request you to release the new version of netcommon.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible/netcommon/plugins/action/network.py 

##### ANSIBLE VERSION

```
The test was done in ansible 2.9.7 with ansible.netcommon version 0.0.2. 
Collections works fine with the ansible version 2.9.7 and ansible.netcommon  0.0.3-dev19 and onwards.
```

**Comment by Qalthos** [comment]
As version 1.0.0 has been released for some time now, I'm going to assume this issue is no longer relevant.
